name: Playwright Tests
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
jobs:
  run-e2e-tests:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Install dependencies
        run: yarn add ci && npx playwright install-deps && yarn playwright install
      - name: Run tests
        run: yarn playwright test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
